### ISSUE TITLE
Move the CI server, change NuGet Gallery account

### ISSUE THREAD

**Issue by edandersen** [mdsol/crichton-dotnet#38]
The CI server is still on my Azure account which is tied to my MSDN subscription. It will disappear soon.

Somebody needs to:
- Log in to TeamCity, create a backup of the database via the Web UI
- Remote Desktop into the server and get the backed up database
- Create a new VM (you can use AWS if you want) and install TeamCity on it
- Restore the backup database
- Update the readme etc

I have given @kenyamat all the passwords he needs to do the above.

You also need to move the nuget packages to a different account. You need to:
- Create a user account at www.nuget.org - I would recommend creating a shared mdsol account for future public nuget packages
- Let me know the username and I will transfer Crichton.Representors, Crichton.Client and Crichton.WebApi to that username
- Change the nuget credentials on the TeamCity server

**Comment by kenyamat** [comment]
Hi Ed,

Thank you for your kindly reminder!

_Team City_
I just got a backup from Team City and will try to set up a new Jenkins CI
on AWS.

_Nuget_
We just created a new shared account (Medidata), could you please transfer
them to the account?

Thanks,
Kenya

2014-07-06 8:27 GMT+09:00 Ed Andersen notifications@github.com:

**Comment by kenyamat** [comment]
Yo

I’ve added “Medidata” to the list of Owners on:

https://www.nuget.org/packages/Crichton.Client/
https://www.nuget.org/packages/Crichton.Representors
https://www.nuget.org/packages/Crichton.WebApi

Once you’ve approved being added to the list of owners, you can remove “edandersen” from the list of owners.

Best
Ed

On Jul 7, 2014, at 10:23 AM, Kenya Matsumoto <kmatsumoto@mdsol.com<mailto:kmatsumoto@mdsol.com>> wrote:

Hi Ed,

Thank you for your kindly reminder!

Team City
I just got a backup from Team City and will try to set up a new Jenkins CI on AWS.

Nuget
We just created a new shared account (Medidata), could you please transfer them to the account?

Thanks,
Kenya

2014-07-06 8:27 GMT+09:00 Ed Andersen <notifications@github.com<mailto:notifications@github.com>>:

The CI server is still on my Azure account which is tied to my MSDN subscription. It will disappear soon.

Somebody needs to:
-   Log in to TeamCity, create a backup of the database via the Web UI
-   Remote Desktop into the server and get the backed up database
-   Create a new VM (you can use AWS if you want) and install Jenkins on it
-   Restore the backup database
-   Update the readme etc

I have given @kenyamathttps://github.com/kenyamat all the passwords he needs to do the above.

You also need to move the nuget packages to a different account. You need to:
-   Create a user account at www.nuget.orghttp://www.nuget.org/ - I would recommend creating a shared mdsol account for future public nuget packages
-   Let me know the username and I will transfer Crichton.Representors, Crichton.Client and Crichton.WebApi to that username
-   Change the nuget credentials on the TeamCity server

**Comment by kenyamat** [comment]
Oh and my instructions are wrong - you don’t want to install Jenkins in AWS, install another TeamCity server or the backup won’t work.

On Jul 7, 2014, at 10:23 AM, Kenya Matsumoto <kmatsumoto@mdsol.com<mailto:kmatsumoto@mdsol.com>> wrote:

Hi Ed,

Thank you for your kindly reminder!

Team City
I just got a backup from Team City and will try to set up a new Jenkins CI on AWS.

Nuget
We just created a new shared account (Medidata), could you please transfer them to the account?

Thanks,
Kenya

2014-07-06 8:27 GMT+09:00 Ed Andersen <notifications@github.com<mailto:notifications@github.com>>:

The CI server is still on my Azure account which is tied to my MSDN subscription. It will disappear soon.

Somebody needs to:
-   Log in to TeamCity, create a backup of the database via the Web UI
-   Remote Desktop into the server and get the backed up database
-   Create a new VM (you can use AWS if you want) and install Jenkins on it
-   Restore the backup database
-   Update the readme etc

I have given @kenyamathttps://github.com/kenyamat all the passwords he needs to do the above.

You also need to move the nuget packages to a different account. You need to:
-   Create a user account at www.nuget.orghttp://www.nuget.org/ - I would recommend creating a shared mdsol account for future public nuget packages
-   Let me know the username and I will transfer Crichton.Representors, Crichton.Client and Crichton.WebApi to that username
-   Change the nuget credentials on the TeamCity server

**Comment by edandersen** [comment]
@kenyamat it's best to reply directly in Github rather than use the email system. I also cannot reply to w3schools any more.

Let me know if you have any other problems.

**Comment by kenyamat** [comment]
Thank you for you prompt action! Ed!!

2014-07-07 10:39 GMT+09:00 Ed Andersen notifications@github.com:

**Comment by edandersen** [comment]
@kenyamat Miss you Kenya!!

**Comment by kenyamat** [comment]
@edandersen Hey Ed,
I've completed migration of the CI onto my Azure.
Please close the issue!

By the way, I finally found this Issue tracker feature on GitHub!
